import { Command } from 'commander';
import { promises as fs } from 'fs';
import path from 'path';
import YAML from 'yaml';
const parseYaml = YAML.parse;
import pc from 'picocolors';
import {
  FlowTestOrchestrator,
  DiscoveryAgent,
  TestPlanner,
  KeyResolver,
  createAIProvider,
  MockAIProvider,
  HubIngestClient,
  SafePublicCrawler,
  BenchmarkingEngine,
  UXGapSynthesizer,
  pushRunToHub,
  syncFigma,
} from '@qa/core';

import { DashboardServer } from '@qa/dashboard';
import { HubServer, PostgresHubDatabase } from '@qa/hub';
import { RunnerServer, defaultUiApps } from '@qa/runner';
import crypto from 'crypto';
import type { SpecFile, ProductProfile, ReleaseReport, DiscoveryDraft, AIProviderType } from '@qa/types';
import { chromium } from 'playwright';


const program = new Command();

program
  .name('qa-test')
  .description('Pre-Release Readiness Checker - AI-Driven QA Flow Testing Engine')
  .version('0.2.0');

// Command: run
program
  .command('run')
  .description('Execute full pre-release readiness checks against a target URL')
  .requiredOption('-u, --url <url>', 'Target staging or tunnel URL (e.g. http://localhost:3000)')
  .option('-p, --product <id>', 'Product identifier', 'default-product')
  .option('-s, --spec <path>', 'Path to test case spec file (JSON or YAML)')
  .option('-c, --config <path>', 'Path to product profile config file')
  .option('--ai', 'Automatically discover flows using AI prior to execution')
  .option('--context <path>', 'Path to PRD / Product Context for AI discovery')
  .option('--ai-provider <provider>', 'AI provider (anthropic, openai, gemini, openrouter, mock)')
  .option('--api-key <key>', 'API key for AI provider')
  .option('--ai-model <model>', 'Override the default model used for AI discovery')
  .option('--tunnel-auth <token>', 'Dev tunnel authorization token')
  .option('--no-headless', 'Run browser in headed mode')
  .option('-o, --output <dir>', 'Output directory for reports', '.qa-report')
  .option('--dashboard', 'Open local review dashboard after test execution')
  .option('--dashboard-port <port>', 'Port for dashboard if --dashboard is enabled', '3000')
  .option('--all-breakpoints', 'Run checks across all breakpoints (375px, 768px, 1440px)')
  .option('--breakpoints <list>', 'Comma-separated breakpoints list (e.g. 375px,1440px)')
  .option('--hub <url>', 'Report Hub server URL (e.g. http://localhost:3001)')
  .option('--hub-token <token>', 'Product-scoped ingest token for Report Hub')
  .option('--release <target>', 'Release target name (e.g. v1.2.0-rc1)', 'latest')
  .option('--update-baselines', 'Save this run\'s final screens as the approved visual baselines instead of diffing')
  .option('--no-video', 'Do not record session video for failed test points')
  .action(async (options) => {
    console.log(pc.cyan(`\n🔍 QA Pre-Release Readiness Checker v0.3.0`));
    console.log(pc.gray(`Target: ${options.url} | Product: ${options.product}\n`));


    try {
      let profile: ProductProfile | undefined;
      if (options.config) {
        const cfgContent = await fs.readFile(options.config, 'utf8');
        profile = parseYaml(cfgContent);
      }

      let specTestCases = [];
      let usedFallbackDiscovery = false;

      if (options.ai) {
        console.log(pc.cyan(`\n🤖 Running AI Discovery Pipeline...`));
        const keyResolver = new KeyResolver();
        const resolved = await keyResolver.resolveKey(options.aiProvider, options.apiKey);
        const providerType: AIProviderType = resolved?.provider || options.aiProvider || 'mock';
        const apiKey = resolved?.apiKey || options.apiKey || 'mock-key';

        if (!resolved && providerType !== 'mock') {
          console.log(pc.yellow(`⚠️ No API key found for ${providerType}. Falling back to MockAIProvider.`));
        }

        const aiProvider = createAIProvider(providerType, apiKey, undefined, options.aiModel);
        const agent = new DiscoveryAgent();
        const draft = await agent.discover({
          targetUrl: options.url,
          productId: options.product,
          profile,
          contextFilePath: options.context,
          outputDir: options.output,
          aiProvider,
        });

        const planner = new TestPlanner();
        const generatedSpec = planner.plan(draft);
        specTestCases = generatedSpec.testCases;
        console.log(pc.green(`✔ AI generated ${specTestCases.length} test cases from ${draft.flows.length} flows.\n`));
        usedFallbackDiscovery = !!draft.usedFallbackSynthesis;
        if (usedFallbackDiscovery) {
          console.log(
            pc.yellow(
              `⚠️ AI discovery did not produce usable flows — test cases were generated by the generic template fallback, not real AI analysis. Findings below may not reflect the app's actual behavior.`
            )
          );
        }
      } else if (options.spec) {
        const specContent = await fs.readFile(options.spec, 'utf8');
        const parsed: SpecFile = options.spec.endsWith('.yaml') || options.spec.endsWith('.yml')
          ? parseYaml(specContent)
          : JSON.parse(specContent);
        specTestCases = parsed.testCases || [];
      } else {
        // Fallback default test case
        specTestCases = [
          {
            id: 'TC-DEFAULT-001',
            flowId: 'landing-verification',
            name: 'Home page sanity check',
            role: 'anonymous',
            startPage: '/',
            steps: [
              { action: 'wait' as const, name: 'Wait for page load' },
            ],
            expectations: {
              url: { pattern: '/*' },
            },
          },
        ];
      }

      let breakpoints: any = ['1440px'];
      if (options.allBreakpoints) {
        breakpoints = ['375px', '768px', '1440px'];
      } else if (options.breakpoints) {
        breakpoints = options.breakpoints.split(',').map((b: string) => b.trim());
      }

      const orchestrator = new FlowTestOrchestrator();
      const report: ReleaseReport = await orchestrator.run({
        targetUrl: options.url,
        productId: options.product,
        specTestCases,
        profile,
        headless: options.headless,
        tunnelAuth: options.tunnelAuth,
        outputDir: options.output,
        breakpoints,
        repoRoot: process.cwd(),
        recordVideo: options.video,
        updateBaselines: options.updateBaselines,
      });
      report.usedFallbackDiscovery = usedFallbackDiscovery;
      if (options.updateBaselines) {
        console.log(pc.cyan(`📸 Visual baselines updated in ${profile?.visualBaselineDir || '.qa-baselines'}`));
      }

      console.log(pc.green(`\n✔ QA Run completed in ${(report.durationMs / 1000).toFixed(1)}s`));
      console.log(pc.bold(`Findings: ${report.findings.length} total`));
      if (report.usedFallbackDiscovery) {
        console.log(
          pc.yellow(`⚠️ This run used the fallback test generator, not AI discovery — see report.md for details.`)
        );
      }
      
      const blockers = report.findings.filter((f) => f.severity === 'Blocker');
      if (blockers.length > 0) {
        console.log(pc.red(pc.bold(`✖ ${blockers.length} BLOCKERS FOUND! Release is NOT recommended.`)));
      } else {
        console.log(pc.green(pc.bold(`✔ Zero blockers found. Release ready!`)));
      }

      console.log(pc.cyan(`\nReports generated:`));
      console.log(`  📄 Markdown: ${path.join(options.output, 'report.md')}`);
      console.log(`  📊 JSON:     ${path.join(options.output, 'findings.json')}\n`);

      if (options.hub) {
        console.log(pc.cyan(`\n☁ Syncing run results to Report Hub (${options.hub})...`));
        const uploadRes = await pushRunToHub(report, {
          hubUrl: options.hub,
          hubToken: options.hubToken,
          outputDir: options.output,
          releaseTarget: options.release || 'latest',
        });
        if (uploadRes.synced) {
          console.log(pc.green(`✔ Run successfully consolidated into Report Hub!`));
          console.log(`  🌐 Hub URL: ${pc.bold(pc.underline(uploadRes.hubViewUrl || options.hub))}\n`);
        } else if (uploadRes.authFailed) {
          console.log(pc.red(`✖ Hub rejected this run: ${uploadRes.error}`));
          console.log(pc.gray(`  Provide a valid token with --hub-token, or provision one via: qa-test hub create-token --product ${options.product}\n`));
        } else if (uploadRes.queued) {
          console.log(pc.yellow(`⚠️ Hub temporarily unreachable. Run saved to local outbox (ID: ${uploadRes.outboxId}).`));
          console.log(pc.gray(`  Will auto-sync on next online run or via: qa-test hub sync --hub ${options.hub}\n`));
        }
      }

      if (options.dashboard) {
        const port = parseInt(options.dashboardPort, 10) || 3000;
        const server = new DashboardServer({
          port,
          reportDir: options.output,
        });
        const url = await server.start();
        console.log(pc.cyan(`\n🚀 Local Review Dashboard running at:`), pc.bold(pc.underline(url)));
        console.log(pc.gray(`Press Ctrl+C to stop the dashboard server.\n`));
      }

    } catch (err: unknown) {
      console.error(pc.red(`\n✖ Execution failed:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: dashboard
program
  .command('dashboard')
  .description('Launch the local QA review web dashboard')
  .option('-p, --port <port>', 'Port to serve dashboard on', '3000')
  .option('-d, --dir <dir>', 'Reports directory', '.qa-report')
  .action(async (options) => {
    const port = parseInt(options.port, 10) || 3000;
    const reportDir = options.dir || '.qa-report';

    console.log(pc.cyan(`\n🚀 Starting QA Local Review Dashboard...`));
    console.log(pc.gray(`Report Source: ${path.resolve(reportDir)}`));

    try {
      const server = new DashboardServer({
        port,
        reportDir,
      });

      const url = await server.start();
      console.log(pc.green(`✔ Dashboard is LIVE at:`), pc.bold(pc.underline(url)));
      console.log(pc.gray(`Press Ctrl+C to terminate.\n`));
    } catch (err: any) {
      console.error(pc.red(`Failed to start dashboard:`), err.message);
      process.exit(1);
    }
  });

// Command: verify
program
  .command('verify <findingId>')
  .description('Verify whether a specific finding has been fixed by re-running its test point')
  .option('-o, --output <dir>', 'Reports directory', '.qa-report')
  .option('-s, --spec <path>', 'Spec file path (optional, will attempt reading default or previous run)')
  .action(async (findingId, options) => {
    console.log(pc.cyan(`\n🔍 Verifying finding: ${findingId}`));
    const reportDir = options.output || '.qa-report';
    const findingsJsonPath = path.join(reportDir, 'findings.json');

    try {
      const content = await fs.readFile(findingsJsonPath, 'utf8');
      const report: ReleaseReport = JSON.parse(content);
      const finding = report.findings.find((f) => f.id === findingId);

      if (!finding) {
        console.error(pc.red(`Finding ${findingId} not found in ${findingsJsonPath}`));
        process.exit(1);
      }

      console.log(pc.bold(`Title:`), finding.title);
      console.log(pc.bold(`Checker:`), finding.checker);
      console.log(pc.bold(`Location:`), finding.where.urlPath);
      console.log(pc.bold(`Role:`), finding.where.role);
      console.log(pc.bold(`Breakpoint:`), finding.where.breakpoint);

      let targetTestCase: any;
      if (options.spec) {
        const specContent = await fs.readFile(options.spec, 'utf8');
        const parsed = options.spec.endsWith('.yaml') || options.spec.endsWith('.yml')
          ? parseYaml(specContent)
          : JSON.parse(specContent);
        targetTestCase = parsed.testCases?.find((t: any) => t.id === finding.testCaseId);
      }

      if (!targetTestCase) {
        // Fallback test case from finding information
        targetTestCase = {
          id: finding.testCaseId || 'TC-VERIFY',
          flowId: finding.flowId || 'verify-flow',
          name: `Verification for ${findingId}`,
          role: finding.where.role || 'anonymous',
          startPage: finding.where.urlPath,
          steps: [{ action: 'wait', name: 'Wait for page load' }],
          expectations: {
            url: { pattern: '/*' },
          },
        };
      }

      console.log(pc.gray(`Re-running test point ${targetTestCase.id}...`));
      const orchestrator = new FlowTestOrchestrator();
      const verifyReport = await orchestrator.run({
        targetUrl: report.targetUrl,
        productId: report.productId,
        specTestCases: [targetTestCase],
        outputDir: path.join(reportDir, '.verify-tmp'),
        breakpoints: [finding.where.breakpoint],
        repoRoot: process.cwd(),
      });

      // Check if this finding re-occurred
      const stillFailing = verifyReport.findings.some(
        (f) => f.title === finding.title && f.where.urlPath === finding.where.urlPath
      );

      if (!stillFailing) {
        console.log(pc.green(pc.bold(`\n✔ Finding ${findingId} verified as FIXED!`)));
        finding.triageStatus = 'Resolved';
        await fs.writeFile(findingsJsonPath, JSON.stringify(report, null, 2), 'utf8');

        // Update report.md
        const { ReportGenerator } = await import('@qa/core');
        const reportGen = new ReportGenerator(reportDir);
        await reportGen.generate(report);
        console.log(pc.gray(`Updated status to "Resolved" in ${findingsJsonPath} and report.md\n`));
      } else {
        console.log(pc.red(pc.bold(`\n✖ Finding ${findingId} STILL FAILS.`)));
        console.log(pc.yellow(`Expected: ${finding.expectedVsActual.expected}`));
        console.log(pc.yellow(`Resolution hint: ${finding.resolution}\n`));
        process.exit(1);
      }
    } catch (err: unknown) {
      console.error(pc.red(`Verification error:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: discover
program
  .command('discover')
  .description('Discover flows, extract requirements, and open the confirmation review dashboard')
  .requiredOption('-u, --url <url>', 'Target staging or tunnel URL (e.g. http://localhost:3000)')
  .option('-p, --product <id>', 'Product identifier', 'default-product')
  .option('-c, --config <path>', 'Path to product profile config file')
  .option('--context <path>', 'Path to Product Context (PRD, user stories markdown)')
  .option('--ai-provider <provider>', 'AI provider (anthropic, openai, gemini, openrouter, mock)')
  .option('--api-key <key>', 'API key for AI provider')
  .option('--ai-model <model>', 'Override the default model used for AI discovery')
  .option('-o, --output <dir>', 'Output directory for discovery draft', '.qa-report')
  .option('--no-dashboard', 'Do not launch confirmation dashboard after discovery')
  .option('--dashboard-port <port>', 'Port for confirmation dashboard', '3000')
  .action(async (options) => {
    console.log(pc.cyan(`\n🔍 QA AI Flow Discovery v0.2.0`));
    console.log(pc.gray(`Target: ${options.url} | Product: ${options.product}\n`));

    try {
      let profile: ProductProfile | undefined;
      if (options.config) {
        const cfgContent = await fs.readFile(options.config, 'utf8');
        profile = parseYaml(cfgContent);
      }

      const keyResolver = new KeyResolver();
      const resolved = await keyResolver.resolveKey(options.aiProvider, options.apiKey);
      const providerType: AIProviderType = resolved?.provider || options.aiProvider || 'mock';
      const apiKey = resolved?.apiKey || options.apiKey || 'mock-key';

      if (!resolved && providerType !== 'mock') {
        console.log(pc.yellow(`⚠️ No API key found for ${providerType}. Falling back to MockAIProvider.`));
      }

      const aiProvider = createAIProvider(providerType, apiKey, undefined, options.aiModel);
      const agent = new DiscoveryAgent();
      const draft = await agent.discover({
        targetUrl: options.url,
        productId: options.product,
        profile,
        contextFilePath: options.context,
        outputDir: options.output,
        aiProvider,
      });

      console.log(pc.green(`\n✔ Discovery completed!`));
      console.log(`  📄 Discovered Flows: ${draft.flows.length}`);
      console.log(`  🌐 Reachable Pages:  ${draft.pages.length}`);
      console.log(`  ⚠️ Ambiguity Items:  ${draft.ambiguityQuestions.length}`);
      console.log(`  📁 Draft location:   ${path.join(options.output, 'discovery-draft.json')}\n`);
      if (draft.usedFallbackSynthesis) {
        console.log(
          pc.yellow(
            `⚠️ AI discovery did not produce usable flows — this draft was generated by the generic template fallback, not real AI analysis.`
          )
        );
      }

      if (options.dashboard) {
        const port = parseInt(options.dashboardPort, 10) || 3000;
        const server = new DashboardServer({
          port,
          reportDir: options.output,
        });
        const url = await server.start();
        console.log(pc.cyan(`🚀 Confirmation Dashboard running at:`), pc.bold(pc.underline(`${url}/confirm`)));
        console.log(pc.gray(`Review discovered flows, resolve ambiguities, and approve test cases.`));
        console.log(pc.gray(`Press Ctrl+C to terminate dashboard.\n`));
      }
    } catch (err: unknown) {
      console.error(pc.red(`\n✖ Discovery failed:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: plan
program
  .command('plan')
  .description('Compile confirmed discovery draft into an executable test case spec')
  .option('-d, --draft <path>', 'Path to discovery draft file', '.qa-report/discovery-draft.json')
  .option('-o, --output <path>', 'Output spec file path', 'qa.spec.json')
  .action(async (options) => {
    console.log(pc.cyan(`\n📐 QA Spec Planner v0.2.0`));
    try {
      const draftContent = await fs.readFile(options.draft, 'utf8');
      const draft: DiscoveryDraft = JSON.parse(draftContent);

      const planner = new TestPlanner();
      const spec = planner.plan(draft);
      await planner.saveSpecFile(spec, options.output);

      console.log(pc.green(`✔ Successfully generated ${options.output} with ${spec.testCases.length} test cases.\n`));
      console.log(pc.gray(`You can now execute:`));
      console.log(pc.bold(`  qa-test run -u ${draft.targetUrl} -s ${options.output}\n`));
    } catch (err: unknown) {
      console.error(pc.red(`Failed to plan spec:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: init
program
  .command('init')
  .description('Initialize a sample QA spec and config in the current directory')
  .action(async () => {
    const sampleSpec: SpecFile = {
      version: '1.0',
      product: 'my-product',
      testCases: [
        {
          id: 'TC-001',
          flowId: 'authentication',
          name: 'Sign in flow',
          role: 'member',
          startPage: '/login',
          steps: [
            { action: 'fill', selector: '[data-testid="email-input"]', value: 'user@example.com', name: 'Enter email' },
            { action: 'fill', selector: '[data-testid="password-input"]', value: 'secret123', name: 'Enter password' },
            { action: 'click', selector: '[data-testid="submit-btn"]', name: 'Click submit' },
          ],
          expectations: {
            url: { pattern: '/dashboard*' },
            text: { contains: 'Welcome back' },
          },
        },
      ],
    };

    await fs.writeFile('qa.spec.json', JSON.stringify(sampleSpec, null, 2), 'utf8');
    console.log(pc.green(`✔ Created qa.spec.json`));
  });

// Command group: hub
const hubCommand = program.command('hub').description('Manage central QA Report Hub and offline outbox');

hubCommand
  .command('start')
  .description('Launch the Report Hub server')
  .option('-p, --port <port>', 'Port to serve Hub on', '4000')
  .option('-h, --host <host>', 'Host to bind Hub to', 'localhost')
  .option('--db <url>', 'Postgres connection string (overrides DATABASE_URL)')
  .action(async (options) => {
    const port = parseInt(options.port, 10) || 4000;
    const host = options.host || 'localhost';
    console.log(pc.cyan(`\n🚀 Starting QA Report Hub Server...`));
    try {
      const dbUrl = options.db || process.env.DATABASE_URL;
      const db = dbUrl ? new PostgresHubDatabase(dbUrl) : undefined;
      if (db) {
        console.log(pc.gray(`Persisting to Postgres (${dbUrl.replace(/:\/\/[^@]+@/, '://***@')})`));
      } else {
        console.log(
          pc.yellow(`⚠️ No DATABASE_URL or --db set — using in-memory storage. All runs/findings are lost on restart.`)
        );
      }
      const server = new HubServer({ port, host, db });
      const url = await server.start();
      console.log(pc.green(`✔ Report Hub is LIVE at:`), pc.bold(pc.underline(`${url}/hub`)));
      console.log(pc.gray(`API endpoints ready. Press Ctrl+C to terminate.\n`));
    } catch (err: unknown) {
      console.error(pc.red(`Failed to start Hub server:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

hubCommand
  .command('create-token')
  .description('Provision a product-scoped ingest token for the Report Hub (requires a Postgres-backed Hub)')
  .requiredOption('-p, --product <id>', 'Product identifier to scope this token to')
  .option('-l, --label <label>', 'Human-readable label for this token', 'default')
  .option('--db <url>', 'Postgres connection string (overrides DATABASE_URL)')
  .action(async (options) => {
    const dbUrl = options.db || process.env.DATABASE_URL;
    if (!dbUrl) {
      console.error(
        pc.red(
          `A Postgres connection is required to provision a durable token (pass --db or set DATABASE_URL). An in-memory Hub cannot be provisioned from a separate process.`
        )
      );
      process.exit(1);
    }
    const db = new PostgresHubDatabase(dbUrl);
    const existing = await db.getProduct(options.product);
    if (!existing) {
      await db.createProduct({ id: options.product, name: options.product, createdAt: new Date().toISOString() });
    }
    const token = crypto.randomBytes(24).toString('hex');
    await db.createToken({ token, productId: options.product, label: options.label, createdAt: new Date().toISOString() });
    console.log(pc.green(`✔ Token created for product "${options.product}"`));
    console.log(`  ${pc.bold(token)}`);
    console.log(pc.gray(`\nUse it with: qa-test run ... --hub <url> --hub-token ${token}\n`));
  });

hubCommand
  .command('sync')
  .description('Synchronize pending runs from local outbox queue to the Report Hub')
  .requiredOption('--hub <url>', 'Report Hub server URL')
  .option('--token <token>', 'Product-scoped ingest token')
  .action(async (options) => {
    console.log(pc.cyan(`\n🔄 Synchronizing local outbox to Report Hub (${options.hub})...`));
    const hubClient = new HubIngestClient({
      hubUrl: options.hub,
      token: options.token,
    });
    const result = await hubClient.syncOutbox();
    if (result.syncedCount > 0) {
      console.log(pc.green(`✔ Successfully synchronized ${result.syncedCount} pending run(s)!`));
    } else {
      console.log(pc.gray(`No pending runs to sync.`));
    }
    if (result.failedCount > 0) {
      console.log(pc.yellow(`⚠️ ${result.failedCount} run(s) failed to sync and remain in outbox.`));
    }
  });

// Command group: figma
const figmaCommand = program.command('figma').description('Snapshot Figma design tokens and baselines for offline checks');

figmaCommand
  .command('sync')
  .description('Export Figma variables to design-tokens.json (and optional frames as visual baselines)')
  .requiredOption('-f, --file <key>', 'Figma file key (from the file URL: figma.com/design/<key>/...)')
  .option('--token <token>', 'Figma personal access token (defaults to FIGMA_TOKEN env var)')
  .option('--out <path>', 'Where to write the tokens file', 'design-tokens.json')
  .option(
    '--frame <nodeId=name>',
    'Export a frame as baseline <name>.png, e.g. 12:34=TC-001-1440px (repeatable)',
    (value: string, acc: string[]) => [...acc, value],
    [] as string[]
  )
  .option('--baseline-dir <dir>', 'Directory for exported frame baselines', '.qa-baselines')
  .action(async (options) => {
    const token = options.token || process.env.FIGMA_TOKEN;
    if (!token) {
      console.error(pc.red(`A Figma token is required: pass --token or set FIGMA_TOKEN.`));
      process.exit(1);
    }
    const frames: Record<string, string> = {};
    for (const spec of options.frame as string[]) {
      const [nodeId, name] = spec.split('=');
      if (!nodeId || !name) {
        console.error(pc.red(`Invalid --frame "${spec}". Expected <nodeId>=<name>, e.g. 12:34=TC-001-1440px`));
        process.exit(1);
      }
      frames[nodeId.trim()] = name.trim();
    }

    console.log(pc.cyan(`\n🎨 Syncing design tokens from Figma file ${options.file}...`));
    try {
      const result = await syncFigma({
        fileKey: options.file,
        token,
        tokensOut: options.out,
        frames,
        baselineDir: options.baselineDir,
      });
      const c = result.tokenCounts;
      console.log(pc.green(`✔ Wrote ${result.tokensPath}`));
      console.log(pc.gray(`  ${c.colors} colors, ${c.borderRadius} radii, ${c.fontSize} font sizes`));
      for (const b of result.baselines) console.log(pc.gray(`  📸 Baseline: ${b}`));
      console.log(pc.gray(`\nReference it from your product config: figmaTokensFile: ${options.out}\n`));
    } catch (err: unknown) {
      console.error(pc.red(`✖ Figma sync failed:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: runner
program
  .command('runner')
  .description('Launch the interactive Runner service used by the web dashboard to trigger live runs')
  .option('-p, --port <port>', 'Port to serve the Runner on', '3001')
  .option('-h, --host <host>', 'Host to bind Runner to', 'localhost')
  .option('-o, --output <dir>', 'Output directory for run evidence/reports', '.qa-runner-report')
  .option('--hub <url>', 'Report Hub that /api/v1/* is passed on to (default: HUB_API_URL)')
  .action(async (options) => {
    const port = parseInt(options.port, 10) || 3001;
    const host = options.host || 'localhost';
    const hubUrl = options.hub || process.env.HUB_API_URL || undefined;
    console.log(pc.cyan(`\n🚀 Starting the QA Tool...`));
    try {
      const server = new RunnerServer({ port, host, outputDir: options.output, hubUrl, ui: defaultUiApps() });
      const url = (await server.start()).replace('://0.0.0.0', '://localhost');
      console.log(pc.green(`✔ Open in your browser:`), pc.bold(pc.underline(`${url}/`)));
      console.log(pc.gray(`Report Hub:     ${hubUrl ?? 'not connected'}`));
      console.log(pc.gray(`Press Ctrl+C to terminate.\n`));
    } catch (err: unknown) {
      console.error(pc.red(`Failed to start Runner:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

// Command: compare
program
  .command('compare')
  .description('Safely benchmark an internal product flow against an external public reference flow')
  .requiredOption('-t, --target <url>', 'Internal target staging / tunnel URL')
  .requiredOption('-r, --reference <url>', 'Public reference / competitor URL')
  .option('-f, --flow <id>', 'Flow identifier (e.g. onboarding, pricing, checkout)', 'onboarding')
  .option('-o, --output <dir>', 'Output directory for benchmark reports', '.qa-compare')
  .option('--ai-provider <provider>', 'AI provider for UX gap synthesis (anthropic, openai, gemini, mock)')
  .option('--api-key <key>', 'API key for AI provider')
  .option('--hub <url>', 'Report Hub server URL for uploading visual benchmark gallery')
  .action(async (options) => {
    console.log(pc.cyan(`\n⚡ QA Competitive Flow Benchmarking v0.4.0`));
    console.log(pc.gray(`Target:    ${options.target}`));
    console.log(pc.gray(`Reference: ${options.reference}`));
    console.log(pc.gray(`Flow:      ${options.flow}\n`));

    try {
      const crawler = new SafePublicCrawler();
      console.log(pc.cyan(`🔍 [1/4] Crawling our internal flow...`));
      const ourFlow = await crawler.crawl({
        entryUrl: options.target,
        flowName: 'Our Flow',
        outputDir: path.join(options.output, 'our'),
        // Our own staging sites commonly disallow all crawlers; robots.txt is for external sites.
        respectRobots: false,
      });

      console.log(pc.cyan(`🌐 [2/4] Crawling external reference flow in Safe Interaction Mode...`));
      const refFlow = await crawler.crawl({
        entryUrl: options.reference,
        flowName: 'Competitor Reference',
        outputDir: path.join(options.output, 'reference'),
      });

      console.log(pc.cyan(`📊 [3/4] Calculating multi-dimensional friction scorecards...`));
      const engine = new BenchmarkingEngine();
      const ourScore = engine.calculateScorecard(ourFlow);
      const refScore = engine.calculateScorecard(refFlow);

      console.log(pc.cyan(`🤖 [4/4] Synthesizing AI UX Gap Analysis...`));
      const keyResolver = new KeyResolver();
      const resolved = await keyResolver.resolveKey(options.aiProvider, options.apiKey);
      const providerType: AIProviderType = resolved?.provider || options.aiProvider || 'mock';
      const apiKey = resolved?.apiKey || options.apiKey || 'mock-key';
      const aiProvider = createAIProvider(providerType, apiKey);

      const synthesizer = new UXGapSynthesizer();
      const recommendations = await synthesizer.synthesize(
        ourFlow,
        refFlow,
        ourScore,
        refScore,
        aiProvider
      );

      const benchmark = engine.compareFlows(options.flow, ourFlow, refFlow, recommendations);

      // Save local artifacts
      await fs.mkdir(options.output, { recursive: true });
      const jsonPath = path.join(options.output, 'benchmark.json');
      await fs.writeFile(jsonPath, JSON.stringify(benchmark, null, 2), 'utf8');

      const mdPath = path.join(options.output, 'benchmark.md');
      const mdContent = `# Competitive Flow Benchmark: ${options.flow}

**Date**: ${new Date().toISOString()}  
**Target**: ${options.target}  
**Reference**: ${options.reference}  

## 1. Friction Scorecard Comparison

| Metric | Our Product | Competitor Reference | Delta |
| :--- | :--- | :--- | :--- |
| **Total Steps** | ${ourScore.totalSteps} | ${refScore.totalSteps} | ${benchmark.delta.stepDifference > 0 ? `+${benchmark.delta.stepDifference}` : benchmark.delta.stepDifference} |
| **Total Input Fields** | ${ourScore.totalFields} | ${refScore.totalFields} | ${benchmark.delta.fieldDifference > 0 ? `+${benchmark.delta.fieldDifference}` : benchmark.delta.fieldDifference} |
| **Required Fields** | ${ourScore.requiredFieldsCount} | ${refScore.requiredFieldsCount} | ${ourScore.requiredFieldsCount - refScore.requiredFieldsCount} |
| **Click Depth** | ${ourScore.clickDepth} | ${refScore.clickDepth} | ${ourScore.clickDepth - refScore.clickDepth} |
| **Friction Index** | **${ourScore.frictionIndex}** | **${refScore.frictionIndex}** | **${benchmark.delta.frictionRatio}x** |

## 2. Interactive Pattern Parity

| Pattern | Our Product | Competitor |
| :--- | :---: | :---: |
${benchmark.patterns.map((p) => `| ${p.pattern} | ${p.ourProduct ? '✔' : '✖'} | ${p.referenceProduct ? '✔' : '✖'} |`).join('\n')}

## 3. Prioritized UX Recommendations

${benchmark.recommendations.map((r, i) => `### ${i + 1}. [${r.category}] ${r.title}
- **Impact / Effort**: ${r.impact} Impact | ${r.effort} Effort
- **Rationale**: ${r.rationale}
- **Suggested Action**: ${r.suggestedAction}
`).join('\n')}
`;
      await fs.writeFile(mdPath, mdContent, 'utf8');

      // CLI Output summary
      console.log(pc.green(pc.bold(`\n✔ Competitive Benchmark Completed!`)));
      console.log(`\n┌────────────────────────┬─────────────┬─────────────┐`);
      console.log(`│ Metric                 │ Our Product │ Competitor  │`);
      console.log(`├────────────────────────┼─────────────┼─────────────┤`);
      console.log(`│ Total Steps            │ ${String(ourScore.totalSteps).padEnd(11)} │ ${String(refScore.totalSteps).padEnd(11)} │`);
      console.log(`│ Required Input Fields  │ ${String(ourScore.requiredFieldsCount).padEnd(11)} │ ${String(refScore.requiredFieldsCount).padEnd(11)} │`);
      console.log(`│ Friction Index         │ ${String(ourScore.frictionIndex).padEnd(11)} │ ${String(refScore.frictionIndex).padEnd(11)} │`);
      console.log(`└────────────────────────┴─────────────┴─────────────┘\n`);

      console.log(pc.cyan(`Reports saved:`));
      console.log(`  📄 Markdown: ${mdPath}`);
      console.log(`  📊 JSON:     ${jsonPath}\n`);

      if (options.hub) {
        console.log(pc.cyan(`☁ Uploading benchmark to Report Hub (${options.hub})...`));
        try {
          const res = await fetch(`${options.hub.replace(/\/+$/, '')}/api/v1/benchmarks`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(benchmark),
          });
          if (res.ok) {
            console.log(pc.green(`✔ Benchmark uploaded to Report Hub!`));
            console.log(`  🌐 View Comparison: ${pc.bold(pc.underline(`${options.hub}/compare?id=${benchmark.id}`))}\n`);
          }
        } catch {
          console.log(pc.yellow(`⚠️ Could not upload to Hub server.`));
        }
      }
    } catch (err: unknown) {
      console.error(pc.red(`\n✖ Benchmarking failed:`), err instanceof Error ? err.message : err);
      process.exit(1);
    }
  });

program.parse(process.argv);


